"""initial schema

Revision ID: 2de9b8fd4ba5
Revises: 
Create Date: 2026-07-31 20:35:54.146178
"""
from alembic import op
import sqlalchemy as sa


revision = '2de9b8fd4ba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('clinic_address', sa.Text(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('language_pref', sa.String(length=10), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('consent_version', sa.String(length=10), nullable=True),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('data_deletion_requested', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'phone', name='uq_patient_clinic_phone')
    )
    op.create_index('ix_patient_clinic', 'patients', ['clinic_id'], unique=False)
    op.create_table('patient_intake_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='visitstatus'), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('symptoms_raw', sa.Text(), nullable=True),
    sa.Column('symptoms_structured', sa.JSON(), nullable=True),
    sa.Column('clarifying_qa', sa.JSON(), nullable=True),
    sa.Column('red_flags_detected', sa.JSON(), nullable=True),
    sa.Column('red_flag_dismissed', sa.Boolean(), nullable=True),
    sa.Column('red_flag_dismissed_by', sa.UUID(), nullable=True),
    sa.Column('ai_recommendation', sa.JSON(), nullable=True),
    sa.Column('ai_confidence_score', sa.String(length=10), nullable=True),
    sa.Column('ai_sources_cited', sa.JSON(), nullable=True),
    sa.Column('surveillance_status', sa.String(length=20), nullable=True),
    sa.Column('recovery_trend', sa.String(length=20), nullable=True),
    sa.Column('recovery_anomaly', sa.String(length=20), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('doctor_approved', sa.Boolean(), nullable=True),
    sa.Column('doctor_approved_at', sa.DateTime(), nullable=True),
    sa.Column('doctor_signature', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('followup_type', sa.Enum('day_3', 'day_7', 'day_30', 'custom', name='followuptype'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Enum('improved', 'no_change', 'worsened', 'not_reported', name='outcomeenum'), nullable=True),
    sa.Column('patient_notes', sa.Text(), nullable=True),
    sa.Column('symptom_score', sa.Integer(), nullable=True),
    sa.Column('needs_escalation', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('indexed_to_vectordb', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('remedies', sa.JSON(), nullable=False),
    sa.Column('dietary_advice', sa.Text(), nullable=True),
    sa.Column('lifestyle_advice', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptions')
    op.drop_table('followups')
    op.drop_table('audit_logs')
    op.drop_table('visits')
    op.drop_table('patient_intake_forms')
    op.drop_index('ix_patient_clinic', table_name='patients')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
